SELECT ARPABET,
        (SELECT ROUND(AVG(TOTALSCORE))
              FROM (
                      SELECT PHONEME, TOTALSCORE, USERNAME FROM (PHONEMELESSONSCORE PLS
                          INNER JOIN USERLESSONHISTORY ULH ON ULH.ID = PLS.IDUSERLESSONHISTORY)
                      WHERE ULH.USERNAME = ?
          UNION ALL
          SELECT PHONEMEWORD AS PHONEME, TOTALSCORE, USERNAME
                FROM PHONEMESCORE WHERE USERNAME = ?) AS T WHERE PHONEME = ARPABET)
          AS AVGSCORE
FROM IPAMAPARPABET
  WHERE ISDELETED = FALSE;