SELECT * FROM
  (SELECT O.ROWID as _id,O.ID, O.NAME, O.DESCRIPTION, O.DATECREATED
FROM
  COUNTRYMAPPINGCOURSE AS CMC
    INNER JOIN COURSE AS C ON C.ID = CMC.IDCOURSE
    INNER JOIN COUNTRY AS CT ON CT.ID = CMC.IDCOUNTRY
    INNER JOIN COURSEMAPPINGLEVEL AS CML ON CMC.IDCOURSE = CML.IDCOURSE
    INNER JOIN LEVEL AS L ON L.ID = CML.IDLEVEL
    INNER JOIN COURSEMAPPINGDETAIL as CMD on CMD.IDLEVEL = L.ID
    INNER JOIN OBJECTIVE as O on O.ID = CMD.IDCHILD
WHERE CT.ID = ? AND L.ID = ? AND CMD.ISTEST = '\0'
ORDER BY O.ROWID ASC) AS TMP
WHERE TMP._id > (SELECT ROWID FROM OBJECTIVE WHERE ID = ? LIMIT 1)
LIMIT 1