SELECT * FROM (SELECT LC.ROWID as _id, LC.ID, LC.NAME, LC.DESCRIPTION, LC.DATECREATED, OM.[INDEX]
FROM
  countrymappingcourse AS CMC
    INNER JOIN COURSE AS C ON C.ID = CMC.IDCOURSE
    INNER JOIN COUNTRY AS CT ON CT.ID = CMC.IDCOUNTRY
    INNER JOIN COURSEMAPPINGLEVEL as CML on CMC.IDCOURSE = CML.IDCOURSE
    INNER JOIN LEVEL AS L on L.ID = CML.IDLEVEL
    INNER JOIN COURSEMAPPINGDETAIL as CMD on CMD.IDLEVEL = CML.IDLEVEL
    INNER JOIN objectivemapping AS OM on OM.IDOBJECTIVE = CMD.IDCHILD
    INNER JOIN lessoncollection AS LC ON LC.ID = OM.IDLESSONCOLLECTION
WHERE CMC.IDCOUNTRY = ? AND CMD.IDLEVEL = ? AND CMD.IDCHILD = ? AND CMD.ISTEST = '\0'
ORDER BY OM.[INDEX] ASC) AS TMP WHERE TMP.[INDEX] > (
  SELECT
    OM.[INDEX]
      FROM
      countrymappingcourse AS CMC
      INNER JOIN COURSE AS C ON C.ID = CMC.IDCOURSE
      INNER JOIN COUNTRY AS CT ON CT.ID = CMC.IDCOUNTRY
      INNER JOIN COURSEMAPPINGLEVEL as CML on CMC.IDCOURSE = CML.IDCOURSE
      INNER JOIN LEVEL AS L on L.ID = CML.IDLEVEL
      INNER JOIN COURSEMAPPINGDETAIL as CMD on CMD.IDLEVEL = CML.IDLEVEL
      INNER JOIN objectivemapping AS OM on OM.IDOBJECTIVE = CMD.IDCHILD
      INNER JOIN lessoncollection AS LC ON LC.ID = OM.IDLESSONCOLLECTION
      WHERE CMC.IDCOUNTRY = ? AND CMD.IDLEVEL = ? AND CMD.IDCHILD = ? AND CMD.ISTEST = '\0'
    AND LC.ID = ? LIMIT 1
) LIMIT 1