SELECT WC.ROWID as _id, WC.ID,WC.DEFINITION, WC.MP3PATH, WC.PRONUNCIATION, WC.WORD
FROM
  (wordofquestion AS WOQ INNER JOIN  wordcollection AS WC ON WC.ID = WOQ.IDWORDCOLLECTION)
WHERE
  WOQ.IDQUESTION = ?