SELECT T.ROWID as _id,T.ID, T.NAME, T.DESCRIPTION, T.DATECREATED, T.PERCENTPASS
FROM
  countrymappingcourse AS CMC
    INNER JOIN COURSEMAPPINGLEVEL as CML on CMC.IDCOURSE = CML.IDCOURSE
    INNER JOIN COURSEMAPPINGDETAIL as CMD on CMD.IDLEVEL = CML.IDLEVEL
    INNER JOIN test as T on T.ID = CMD.IDCHILD
WHERE CMC.IDCOUNTRY = ? AND CMD.IDLEVEL = ? AND CMD.ISTEST != '\0'