SELECT L.ROWID AS _id,L.id, L.NAME, L.ISDEMO, L.DESCRIPTION, L.DATECREATED, L.COLOR
FROM
  countrymappingcourse AS CMC
    INNER JOIN coursemappinglevel AS CML ON CMC.IDCOURSE = CML.IDCOURSE
    INNER JOIN level AS L ON L.ID = CML.IDLEVEL
WHERE CMC.IDCOUNTRY = ? AND CML.[index] < (
  SELECT CML.[index]
  FROM countrymappingcourse AS CMC INNER JOIN coursemappinglevel AS CML ON CMC.IDCOURSE = CML.IDCOURSE
  WHERE CMC.IDCOUNTRY = ? AND CML.IDLEVEL = ?
)
ORDER BY CML.[index] DESC LIMIT 1;