SELECT LC.ROWID as _id, LC.ID, LC.NAME, LC.DESCRIPTION, LC.DATECREATED, LC.TITLE
FROM
  countrymappingcourse AS CMC
    INNER JOIN COURSEMAPPINGLEVEL as CML on CMC.IDCOURSE = CML.IDCOURSE
    INNER JOIN COURSEMAPPINGDETAIL as CMD on CMD.IDLEVEL = CML.IDLEVEL
    INNER JOIN objectivemapping AS OM on OM.IDOBJECTIVE = CMD.IDCHILD
    INNER JOIN lessoncollection AS LC ON LC.ID = OM.IDLESSONCOLLECTION
WHERE CMC.IDCOUNTRY = ? AND CMD.IDLEVEL = ? AND CMD.IDCHILD = ? AND CMD.ISTEST = '\0'
ORDER BY LC.ROWID ASC