SELECT * FROM (SELECT LC.ROWID as _id, LC.ID, LC.NAME, LC.DESCRIPTION, LC.DATECREATED
FROM
  countrymappingcourse AS CMC
    INNER JOIN coursemappingdetail as CMD on CMC.IDCOURSE
    INNER JOIN objectivemapping AS OM on OM.IDOBJECTIVE = CMD.IDCHILD
    INNER JOIN lessoncollection AS LC ON LC.ID = OM.IDLESSONCOLLECTION
WHERE CMC.IDCOUNTRY = ? AND CMD.IDLEVEL = ? AND CMD.IDCHILD = ? AND CMD.ISTEST = '\0'
ORDER BY LC.ROWID ASC) AS TMP WHERE TMP._id > (
  SELECT ROWID FROM lessoncollection WHERE ID = ? LIMIT 1
) LIMIT 1