SELECT O.ROWID as _id,O.ID, O.NAME, O.DESCRIPTION, O.DATECREATED
FROM
  countrymappingcourse AS CMC
    INNER JOIN COURSEMAPPINGLEVEL as CML on CMC.IDCOURSE = CML.IDCOURSE
    INNER JOIN COURSEMAPPINGDETAIL as CMD on CMD.IDLEVEL = CML.IDLEVEL
    INNER JOIN objective as O on O.ID = CMD.IDCHILD
WHERE CMC.IDCOUNTRY = ? AND CMD.IDLEVEL = ? AND CMD.ISTEST = '\0'
ORDER BY O.ROWID ASC