# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'AccentEasy' do
    pod 'Google/Analytics'
	pod 'Google/SignIn'
	pod 'ObjectMapper', '~> 1.1'
	pod 'SSZipArchive'
	pod 'SQLite.swift', '~> 0.9.2'
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'FBSDKShareKit'
    pod 'DLHamburguerMenu'
end

target 'AccentEasyTests' do

end

target 'AccentEasyUITests' do

end

