INSERT INTO languages (code, description) 
VALUES 
('EN', 'English'),
('ES', 'Spanish'),
('FR', 'French'),
('DE', 'German'),
('ZH', 'Chinese');

INSERT INTO regions (country, description)
VALUES
('AD','Andorra'),
('AE','United Arab Emirates'),
('AF','Afghanistan'),
('AG','Antigua and Barbuda'),
('AI','Anguilla'),
('AL','Albania'),
('AM','Armenia'),
('AO','Angola'),
('AQ','Antarctica'),
('AR','Argentina'),
('AS','American Samoa'),
('AT','Austria'),
('AU','Australia'),
('AW','Aruba'),
('AX','Aland Islands'),
('AZ','Azerbaijan'),
('BA','Bosnia and Herzegovina'),
('BB','Barbados'),
('BD','Bangladesh'),
('BE','Belgium'),
('BF','Burkina Faso'),
('BG','Bulgaria'),
('BH','Bahrain'),
('BI','Burundi'),
('BJ','Benin'),
('BL','Saint Barthélemy'),
('BM','Bermuda'),
('BN','Brunei Darussalam'),
('BO','Bolivia'),
('BQ','Bonaire, Sint Eustatius and Saba'),
('BR','Brazil'),
('BS','Bahamas'),
('BT','Bhutan'),
('BV','Bouvet Island'),
('BW','Botswana'),
('BY','Belarus'),
('BZ','Belize'),
('CA','Canada'),
('CC','Cocos Islands'),
('CD','Congo'),
('CF','Central African Republic'),
('CG','Congo'),
('CH','Switzerland'),
('CI','Cote d Ivoire'),
('CK','Cook Islands'),
('CL','Chile'),
('CM','Cameroon'),
('CN','China'),
('CO','Colombia'),
('CR','Costa Rica'),
('CU','Cuba'),
('CV','Cape Verde'),
('CW','Curacao'),
('CX','Christmas Island'),
('CY','Cyprus'),
('CZ','Czech Republic'),
('DE','Germany'),
('DJ','Djibouti'),
('DK','Denmark'),
('DM','Dominica'),
('DO','Dominican Republic'),
('DZ','Algeria'),
('EC','Ecuador'),
('EE','Estonia'),
('EG','Egypt'),
('EH','Western Sahara'),
('ER','Eritrea'),
('ES','Spain'),
('ET','Ethiopia'),
('FI','Finland'),
('FJ','Fiji'),
('FK','Falkland Islands'),
('FM','Micronesia'),
('FO','Faroe Islands'),
('FR','France'),
('GA','Gabon'),
('GB','United Kingdom'),
('GD','Grenada'),
('GE','Georgia'),
('GF','French Guiana'),
('GG','Guernsey'),
('GH','Ghana'),
('GI','Gibraltar'),
('GL','Greenland'),
('GM','Gambia'),
('GN','Guinea'),
('GP','Guadeloupe'),
('GQ','Equatorial Guinea'),
('GR','Greece'),
('GS','South Georgia and the South Sandwich Islands'),
('GT','Guatemala'),
('GU','Guam'),
('GW','Guinea-Bissau'),
('GY','Guyana'),
('HK','Hong Kong'),
('HM','Heard Island and McDonald Islands'),
('HN','Honduras'),
('HR','Croatia'),
('HT','Haiti'),
('HU','Hungary'),
('ID','Indonesia'),
('IE','Ireland'),
('IL','Israel'),
('IM','Isle of Man'),
('IN','India'),
('IO','British Indian Ocean Territory'),
('IQ','Iraq'),
('IR','Iran'),
('IS','Iceland'),
('IT','Italy'),
('JE','Jersey'),
('JM','Jamaica'),
('JO','Jordan'),
('JP','Japan'),
('KE','Kenya'),
('KG','Kyrgyzstan'),
('KH','Cambodia'),
('KI','Kiribati'),
('KM','Comoros'),
('KN','Saint Kitts and Nevis'),
('KP','Korea, Democratic Peoples Republic of'),
('KR','Korea, Republic of'),
('KW','Kuwait'),
('KY','Cayman Islands'),
('KZ','Kazakhstan'),
('LA','Lao Peoples Democratic Republic'),
('LB','Lebanon'),
('LC','Saint Lucia'),
('LI','Liechtenstein'),
('LK','Sri Lanka'),
('LR','Liberia'),
('LS','Lesotho'),
('LT','Lithuania'),
('LU','Luxembourg'),
('LV','Latvia'),
('LY','Libya'),
('MA','Morocco'),
('MC','Monaco'),
('MD','Moldova, Republic of'),
('ME','Montenegro'),
('MF','Saint Martin (French part)'),
('MG','Madagascar'),
('MH','Marshall Islands'),
('MK','Macedonia, the former Yugoslav Republic of'),
('ML','Mali'),
('MM','Myanmar'),
('MN','Mongolia'),
('MO','Macao'),
('MP','Northern Mariana Islands'),
('MQ','Martinique'),
('MR','Mauritania'),
('MS','Montserrat'),
('MT','Malta'),
('MU','Mauritius'),
('MV','Maldives'),
('MW','Malawi'),
('MX','Mexico'),
('MY','Malaysia'),
('MZ','Mozambique'),
('NA','Namibia'),
('NC','New Caledonia'),
('NE','Niger'),
('NF','Norfolk Island'),
('NG','Nigeria'),
('NI','Nicaragua'),
('NL','Netherlands'),
('NO','Norway'),
('NP','Nepal'),
('NR','Nauru'),
('NU','Niue'),
('NZ','New Zealand'),
('OM','Oman'),
('PA','Panama'),
('PE','Peru'),
('PF','French Polynesia'),
('PG','Papua New Guinea'),
('PH','Philippines'),
('PK','Pakistan'),
('PL','Poland'),
('PM','Saint Pierre and Miquelon'),
('PN','Pitcairn'),
('PR','Puerto Rico'),
('PS','Palestinian Territory, Occupied'),
('PT','Portugal'),
('PW','Palau'),
('PY','Paraguay'),
('QA','Qatar'),
('RE','Reunion'),
('RO','Romania'),
('RS','Serbia'),
('RU','Russian Federation'),
('RW','Rwanda'),
('SA','Saudi Arabia'),
('SB','Solomon Islands'),
('SC','Seychelles'),
('SD','Sudan'),
('SE','Sweden'),
('SG','Singapore'),
('SH','Saint Helena, Ascension and Tristan da Cunha'),
('SI','Slovenia'),
('SJ','Svalbard and Jan Mayen'),
('SK','Slovakia'),
('SL','Sierra Leone'),
('SM','San Marino'),
('SN','Senegal'),
('SO','Somalia'),
('SR','Suriname'),
('SS','South Sudan'),
('ST','Sao Tome and Principe'),
('SV','El Salvador'),
('SX','Sint Maarten (Dutch part)'),
('SY','Syrian Arab Republic'),
('SZ','Swaziland'),
('TC','Turks and Caicos Islands'),
('TD','Chad'),
('TF','French Southern Territories'),
('TG','Togo'),
('TH','Thailand'),
('TJ','Tajikistan'),
('TK','Tokelau'),
('TL','Timor-Leste'),
('TM','Turkmenistan'),
('TN','Tunisia'),
('TO','Tonga'),
('TR','Turkey'),
('TT','Trinidad and Tobago'),
('TV','Tuvalu'),
('TW','Taiwan, Province of China'),
('TZ','Tanzania, United Republic of'),
('UA','Ukraine'),
('UG','Uganda'),
('UM','United States Minor Outlying Islands'),
('US','United States'),
('UY','Uruguay'),
('UZ','Uzbekistan'),
('VA','Holy See (Vatican City State)'),
('VC','Saint Vincent and the Grenadines'),
('VE','Venezuela, Bolivarian Republic of'),
('VG','Virgin Islands, British'),
('VI','Virgin Islands, U.S.'),
('VN','Viet Nam'),
('VU','Vanuatu'),
('WF','Wallis and Futuna'),
('WS','Samoa'),
('YE','Yemen'),
('YT','Mayotte'),
('ZA','South Africa'),
('ZM','Zambia'),
('ZW','Zimbabwe');

INSERT INTO phonemes (name)
VALUES
('AA'),
('AE'),
('AH'),
('AO'),
('AW'),
('AY'),
('B'),
('CH'),
('D'),
('DH'),
('EH'),
('ER'),
('EY'),
('F'),
('G'),
('HH'),
('IH'),
('IY'),
('JH'),
('K'),
('L'),
('M'),
('N'),
('NG'),
('OW'),
('OY'),
('P'),
('R'),
('S'),
('SH'),
('T'),
('TH'),
('UH'),
('UW'),
('V'),
('W'),
('Y'),
('Z'),
('ZH');

INSERT INTO users (email, password, type, time) 
VALUES
('slt@arctic.cmu', sha1('1234abcd'), '01000000', NOW()); 
('admin@talknicer.net', sha1('1234abcd'), '11111111', NOW()),
('jack@talknicer.net', sha1('1234abcd'), '10000000', NOW()),
('kate@talknicer.net', sha1('1234abcd'), '01000000', NOW()),
('robot@talknicer.net', sha1('1234abcd'), '00100000', NOW()),
('slt@arctic.cmu', sha1('1234abcd'), '01000000', NOW()),
('d1@talknicer.net', sha1('1234abcd'), '01000000', NOW()),
('d2@talknicer.net', sha1('1234abcd'), '01000000', NOW());

LOAD DATA INFILE '/home/li-bo/branch-troy/databases/dicts/d01_words_data.dat' INTO TABLE gsoc.words FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' (name, numpro);

LOAD DATA INFILE '/home/li-bo/branch-troy/databases/dicts/d02_pronuciations_data.dat' INTO TABLE gsoc.pronunciations FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' (wordid, proid, phnid, phnpos);

/*INSERT INTO phrases (name)
VALUES
('It was like the beating of hoofs.'),
('They obeyed him, and went here and there at his commands.'),
('He seemed to fill it with his tremendous vitality.'),
('It was more like sugar.'),
('It is not an attempt to smash the market.'),
('I am sure it must have been some adventure.'),
('The life there was healthful and athletic, but too juvenile.'),
('He knew what taboos he was violating.'),
('Very few people knew of the existence of this law.'),
('They are not biologists nor sociologists.');*/

INSERT INTO phrases (name)
VALUES
('Approach the teaching of pronunciation with more confidence.'),
('Examine why learners fail to achieve good pronunciation.'),
('Seek a solution in building their confidence through a holistic approach.');

INSERT INTO phraseinfo (phraseid, wordpos, wordid, proid, postag)
VALUES
(1, 0, 4527, 0, 'v'),
(1, 1, 110838, 0, 'a'),
(1, 2, 109911, 0, 'n'),
(1, 3, 79147, 0, 'p'),
(1, 4, 88006, 1, 'n'),
(1, 5, 121158, 1, 'p'),
(1, 6, 74396, 0, 'm'),
(1, 7, 22238, 0, 'n'),
(2, 0, 36259, 0, 'v'),
(2, 1, 120306, 0, 'c'),
(2, 2, 63190, 0, 'n'),
(2, 3, 37051, 0, 'v'),
(2, 4, 111875, 0, 'p'),
(2, 5, 617, 0, 'v'),
(2, 6, 44805, 0, 'm'),
(2, 7, 88006, 1, 'n'),
(3, 0, 99171, 0, 'v'),
(3, 1, 1, 0, 'a'),
(3, 2, 103704, 0, 'n'),
(3, 3, 53812, 0, 'p'),
(3, 4, 14875, 0, 'n'),
(3, 5, 110872, 0, 's'),
(3, 6, 22238, 0, 'n'),
(3, 7, 111326, 0, 'p'),
(3, 8, 1, 1, 'a'),
(3, 9, 51196, 0, 'm'),
(3, 10, 4527, 0, 'n');

LOAD DATA INFILE '/home/li-bo/branch-troy/databases/phrases/data.txt' INTO TABLE gsoc.phrasestats FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' (phraseid, phnpos, phnid, acomean, acostd, acomaxz, durmean, durstd, durmaxz);


/*some initial exemplar recordings*/
INSERT INTO recordings (userid, phraseid, time, audio, exemplar)
VALUES
(31, 1, NOW(), '/home/li-bo/web/data/audioRecorder/user31/phrase1.flv', 'y'),
(31, 2, NOW(), '/home/li-bo/web/data/audioRecorder/user31/phrase2.flv', 'y'),
(31, 3, NOW(), '/home/li-bo/web/data/audioRecorder/user31/phrase3.flv', 'y'),
(32, 1, NOW(), '/home/li-bo/web/data/audioRecorder/user32/phrase1.flv', 'y'),
(32, 2, NOW(), '/home/li-bo/web/data/audioRecorder/user32/phrase2.flv', 'y'),
(32, 3, NOW(), '/home/li-bo/web/data/audioRecorder/user32/phrase3.flv', 'y');


